package com.nanosolution.aecontrol.model;
// Generated 30/10/2016 10:28:17 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name="cliente"
    ,catalog="aecontrol"
)
public class Cliente  implements java.io.Serializable {


     private Integer idCliente;
     private String nit;
     private String empresa;
     private String nombre;
     private String apellidos;
     private String telefono;
     private String fax;
     private String direccion;
     private String correo;
     private String sitioWeb;
     private Set <Obra> obras = new HashSet<Obra>(0);
     private int id;

    public Cliente() {
    }


    public Cliente(int id, Integer idCliente, String empresa){
        this.id=id;
        this.idCliente=idCliente;
        this.empresa=empresa;
    }
    
    
    public Cliente(String nit, String empresa, String nombre, String apellidos, String telefono, String direccion) {
        this.nit = nit;
        this.empresa = empresa;
        this.nombre = nombre;
        this.apellidos = apellidos;
        this.telefono = telefono;
        this.direccion = direccion;
    }
    public Cliente(String nit, String empresa, String nombre, String apellidos, String telefono, String fax, String direccion, String correo, String sitioWeb, Set<Obra> obras) {
       this.nit = nit;
       this.empresa = empresa;
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.telefono = telefono;
       this.fax = fax;
       this.direccion = direccion;
       this.correo = correo;
       this.sitioWeb = sitioWeb;
       this.obras = obras;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_cliente", unique=true, nullable=false)
    public Integer getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(Integer idCliente) {
        this.idCliente = idCliente;
    }

    
    @Column(name="nit", nullable=false, length=20)
    public String getNit() {
        return this.nit;
    }
    
    public void setNit(String nit) {
        this.nit = nit;
    }

    
    @Column(name="empresa", nullable=false, length=45)
    public String getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(String empresa) {
        this.empresa = empresa;
    }

    
    @Column(name="nombre", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="apellidos", nullable=false, length=90)
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }

    
    @Column(name="telefono", nullable=false, length=15)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    
    @Column(name="fax", length=15)
    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }

    
    @Column(name="direccion", nullable=false, length=45)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    
    @Column(name="correo", length=45)
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }

    
    @Column(name="sitio_web", length=45)
    public String getSitioWeb() {
        return this.sitioWeb;
    }
    
    public void setSitioWeb(String sitioWeb) {
        this.sitioWeb = sitioWeb;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cliente")
    public Set<Obra> getObras() {
        return this.obras;
    }
    
    public void setObras(Set<Obra> obras) {
        this.obras = obras;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }




}






