package com.nanosolution.aecontrol.model;
// Generated 30/10/2016 10:28:17 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Equipo generated by hbm2java
 */
@Entity
@Table(name="equipo"
    ,catalog="aecontrol"
)
public class Equipo  implements java.io.Serializable {


     private Integer idEquipo;
     private Tipoequipo tipoequipo;
     private String nombre;
     private String codigo;
     private int cantidad;
     private int cantidadStock;
     private int precioAlquiler;
     private Set<Kardex> kardexes = new HashSet<Kardex>(0);

    public Equipo() {
    }

	
    public Equipo(Tipoequipo tipoequipo, String nombre, int cantidad, int cantidadStock, int precioAlquiler) {
        this.tipoequipo = tipoequipo;
        this.nombre = nombre;
        this.cantidad = cantidad;
        this.cantidadStock = cantidadStock;
        this.precioAlquiler = precioAlquiler;
    }
    public Equipo(Tipoequipo tipoequipo, String nombre, String codigo, int cantidad, int cantidadStock, int precioAlquiler, Set<Kardex> kardexes) {
       this.tipoequipo = tipoequipo;
       this.nombre = nombre;
       this.codigo = codigo;
       this.cantidad = cantidad;
       this.cantidadStock = cantidadStock;
       this.precioAlquiler = precioAlquiler;
       this.kardexes = kardexes;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_equipo", unique=true, nullable=false)
    public Integer getIdEquipo() {
        return this.idEquipo;
    }
    
    public void setIdEquipo(Integer idEquipo) {
        this.idEquipo = idEquipo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_tipoequipo", nullable=false)
    public Tipoequipo getTipoequipo() {
        return this.tipoequipo;
    }
    
    public void setTipoequipo(Tipoequipo tipoequipo) {
        this.tipoequipo = tipoequipo;
    }

    
    @Column(name="nombre", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="codigo", length=45)
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    
    @Column(name="cantidad", nullable=false)
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }

    
    @Column(name="cantidad_stock", nullable=false)
    public int getCantidadStock() {
        return this.cantidadStock;
    }
    
    public void setCantidadStock(int cantidadStock) {
        this.cantidadStock = cantidadStock;
    }

    
    @Column(name="precio_alquiler", nullable=false)
    public int getPrecioAlquiler() {
        return this.precioAlquiler;
    }
    
    public void setPrecioAlquiler(int precioAlquiler) {
        this.precioAlquiler = precioAlquiler;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="equipo")
    public Set<Kardex> getKardexes() {
        return this.kardexes;
    }
    
    public void setKardexes(Set<Kardex> kardexes) {
        this.kardexes = kardexes;
    }




}


