package com.nanosolution.aecontrol.model;
// Generated 30/10/2016 10:28:17 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Kardex generated by hbm2java
 */
@Entity
@Table(name="kardex"
    ,catalog="aecontrol"
)
public class Kardex  implements java.io.Serializable {


     private Integer id;
     private Equipo equipo;
     private Obra obra;
     private Transportador transportador;
     private Vehiculo vehiculo;
     private int consecutivo;
     private Date fecha;
     private Integer cantidad;
     private String tipoServicio;
     private String nota;

    public Kardex() {
    }

	
    public Kardex(Obra obra, Transportador transportador, Vehiculo vehiculo, int consecutivo, Date fecha, String tipoServicio) {
        this.obra = obra;
        this.transportador = transportador;
        this.vehiculo = vehiculo;
        this.consecutivo = consecutivo;
        this.fecha = fecha;
        this.tipoServicio = tipoServicio;
    }
    public Kardex(Equipo equipo, Obra obra, Transportador transportador, Vehiculo vehiculo, int consecutivo, Date fecha, Integer cantidad, String tipoServicio, String nota) {
       this.equipo = equipo;
       this.obra = obra;
       this.transportador = transportador;
       this.vehiculo = vehiculo;
       this.consecutivo = consecutivo;
       this.fecha = fecha;
       this.cantidad = cantidad;
       this.tipoServicio = tipoServicio;
       this.nota = nota;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_equipo")
    public Equipo getEquipo() {
        return this.equipo;
    }
    
    public void setEquipo(Equipo equipo) {
        this.equipo = equipo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_obra", nullable=false)
    public Obra getObra() {
        return this.obra;
    }
    
    public void setObra(Obra obra) {
        this.obra = obra;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_transportador", nullable=false)
    public Transportador getTransportador() {
        return this.transportador;
    }
    
    public void setTransportador(Transportador transportador) {
        this.transportador = transportador;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_vehiculo", nullable=false)
    public Vehiculo getVehiculo() {
        return this.vehiculo;
    }
    
    public void setVehiculo(Vehiculo vehiculo) {
        this.vehiculo = vehiculo;
    }

    
    @Column(name="consecutivo", nullable=false)
    public int getConsecutivo() {
        return this.consecutivo;
    }
    
    public void setConsecutivo(int consecutivo) {
        this.consecutivo = consecutivo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha", nullable=false, length=10)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="cantidad")
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }

    
    @Column(name="tipo_servicio", nullable=false, length=45)
    public String getTipoServicio() {
        return this.tipoServicio;
    }
    
    public void setTipoServicio(String tipoServicio) {
        this.tipoServicio = tipoServicio;
    }

    
    @Column(name="nota", length=65535)
    public String getNota() {
        return this.nota;
    }
    
    public void setNota(String nota) {
        this.nota = nota;
    }




}


