package com.nanosolution.aecontrol.model;
// Generated 30/10/2016 10:28:17 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Obra generated by hbm2java
 */
@Entity
@Table(name="obra"
    ,catalog="aecontrol"
)
public class Obra  implements java.io.Serializable {


     private Integer idObra;
     private Cliente cliente;
     private String nombre;
     private String zona;
     private String almacenista;
     private String direccion;
     private String telefono;
     private String corrreo;
     private Set<Kardex> kardexes = new HashSet<Kardex>(0);

    public Obra() {
    }

	
    public Obra(Cliente cliente, String nombre, String zona, String almacenista, String direccion, String telefono, String corrreo) {
        this.cliente = cliente;
        this.nombre = nombre;
        this.zona = zona;
        this.almacenista = almacenista;
        this.direccion = direccion;
        this.telefono = telefono;
        this.corrreo = corrreo;
    }
    public Obra(Cliente cliente, String nombre, String zona, String almacenista, String direccion, String telefono, String corrreo, Set<Kardex> kardexes) {
       this.cliente = cliente;
       this.nombre = nombre;
       this.zona = zona;
       this.almacenista = almacenista;
       this.direccion = direccion;
       this.telefono = telefono;
       this.corrreo = corrreo;
       this.kardexes = kardexes;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_obra", unique=true, nullable=false)
    public Integer getIdObra() {
        return this.idObra;
    }
    
    public void setIdObra(Integer idObra) {
        this.idObra = idObra;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_cliente", nullable=false)
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

    
    @Column(name="nombre", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="zona", nullable=false, length=45)
    public String getZona() {
        return this.zona;
    }
    
    public void setZona(String zona) {
        this.zona = zona;
    }

    
    @Column(name="almacenista", nullable=false, length=45)
    public String getAlmacenista() {
        return this.almacenista;
    }
    
    public void setAlmacenista(String almacenista) {
        this.almacenista = almacenista;
    }

    
    @Column(name="direccion", nullable=false, length=45)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    
    @Column(name="telefono", nullable=false, length=15)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    
    @Column(name="corrreo", nullable=false, length=45)
    public String getCorrreo() {
        return this.corrreo;
    }
    
    public void setCorrreo(String corrreo) {
        this.corrreo = corrreo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="obra")
    public Set<Kardex> getKardexes() {
        return this.kardexes;
    }
    
    public void setKardexes(Set<Kardex> kardexes) {
        this.kardexes = kardexes;
    }




}


