package com.nanosolution.aecontrol.model;
// Generated 30/10/2016 10:28:17 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Transportador generated by hbm2java
 */
@Entity
@Table(name="transportador"
    ,catalog="aecontrol"
    , uniqueConstraints = @UniqueConstraint(columnNames="cedula") 
)
public class Transportador  implements java.io.Serializable {


     private Integer id;
     private String cedula;
     private String nombre;
     private String apellidos;
     private Set<Kardex> kardexes = new HashSet<Kardex>(0);

    public Transportador() {
    }

	
    public Transportador(String cedula, String nombre, String apellidos) {
        this.cedula = cedula;
        this.nombre = nombre;
        this.apellidos = apellidos;
    }
    public Transportador(String cedula, String nombre, String apellidos, Set<Kardex> kardexes) {
       this.cedula = cedula;
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.kardexes = kardexes;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="cedula", unique=true, nullable=false, length=45)
    public String getCedula() {
        return this.cedula;
    }
    
    public void setCedula(String cedula) {
        this.cedula = cedula;
    }

    
    @Column(name="nombre", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="apellidos", nullable=false, length=90)
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="transportador")
    public Set<Kardex> getKardexes() {
        return this.kardexes;
    }
    
    public void setKardexes(Set<Kardex> kardexes) {
        this.kardexes = kardexes;
    }




}


