package com.nanosolution.aecontrol.model;
// Generated 30/10/2016 10:28:17 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Vehiculo generated by hbm2java
 */
@Entity
@Table(name="vehiculo"
    ,catalog="aecontrol"
)
public class Vehiculo  implements java.io.Serializable {


     private Integer id;
     private String tipo;
     private String placa;
     private Set<Kardex> kardexes = new HashSet<Kardex>(0);

    public Vehiculo() {
    }

	
    public Vehiculo(String tipo, String placa) {
        this.tipo = tipo;
        this.placa = placa;
    }
    public Vehiculo(String tipo, String placa, Set<Kardex> kardexes) {
       this.tipo = tipo;
       this.placa = placa;
       this.kardexes = kardexes;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="tipo", nullable=false, length=45)
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    
    @Column(name="placa", nullable=false, length=10)
    public String getPlaca() {
        return this.placa;
    }
    
    public void setPlaca(String placa) {
        this.placa = placa;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="vehiculo")
    public Set<Kardex> getKardexes() {
        return this.kardexes;
    }
    
    public void setKardexes(Set<Kardex> kardexes) {
        this.kardexes = kardexes;
    }




}


